#!/usr/bin/env python
# coding: utf-8

# # Data Science Tools and Ecosystem

# ## Author 
# Jorge A. Borrego

# In this notebook, Data Science Tools and Ecosystem are sumarized.

# ## Objectives:
# - list data science language.
# - list commonly used libraries for Data Scientist. 
# - Do some artithmetic.
# - Do some coding.

# Some of the popular languages that Data Scientist use are:
# 1. Python
# 2. Java
# 3. C++

# Some of the commonly used libraries used by Data Scientist include: 
# 1. Matplotlib
# 2. TensorFlow
# 3. NumPy
# 

# | Data Science Tools |
# | --- |
# | Appache Spark |
# | --- |
# | Rstudio|
# | --- |
# | Hadoop|

# ### Below are a few examples of evaluating arithmetic expressions in Python

# In[1]:


(3*4)+5


# In[46]:


x = float(input())
y = float(x/60.0)
#This will convert 200 minutes into hours by dividing by 60.
print(x,"minutes is ", y,"hours!")


# In[ ]:

